#!/bin/bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_DIR="$SCRIPT_DIR/local"

echo -e "${BLUE}=== Agent Config Installation ===${NC}"
echo ""

# Check if local/obsidian.yaml already exists
if [ -f "$LOCAL_DIR/obsidian.yaml" ]; then
    echo -e "${YELLOW}local/obsidian.yaml already exists.${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${GREEN}Keeping existing configuration.${NC}"
        exit 0
    fi
fi

# Standard vault path (single shared location)
VAULT_PATH="$HOME/.obsidian/Obsidian Vault"
echo -e "${BLUE}Vault location:${NC} $VAULT_PATH"
echo ""

# Create vault directory if needed
if [ ! -d "$VAULT_PATH" ]; then
    echo -e "${YELLOW}Creating vault directory...${NC}"
    mkdir -p "$VAULT_PATH"
    echo -e "${GREEN}Created.${NC}"
fi

# Get session prefix
read -p "Session ID prefix [opc]: " SESSION_PREFIX
SESSION_PREFIX="${SESSION_PREFIX:-opc}"

# Get default confidence
read -p "Default confidence (1-10) [7]: " DEFAULT_CONFIDENCE
DEFAULT_CONFIDENCE="${DEFAULT_CONFIDENCE:-7}"

# Get confidence threshold for inbox
read -p "Inbox confidence threshold (1-10) [5]: " CONFIDENCE_THRESHOLD
CONFIDENCE_THRESHOLD="${CONFIDENCE_THRESHOLD:-5}"

# Create local/obsidian.yaml
cat > "$LOCAL_DIR/obsidian.yaml" << EOF
# Obsidian Local Configuration
# Generated by install.sh on $(date -Iseconds)

vault_path: $VAULT_PATH

session_prefix: $SESSION_PREFIX

default_confidence: $DEFAULT_CONFIDENCE

default_priority: 5

inbox:
  confidence_threshold: $CONFIDENCE_THRESHOLD
  review_reminder_days: 7

git:
  auto_commit: true
  commit_prefix: "vault:"

mcp:
  enabled: false

dataview:
  max_results: 50
  default_sort: created

tags:
  auto_tags: []
EOF

echo ""
echo -e "${GREEN}Configuration saved to local/obsidian.yaml${NC}"

# Optionally set up vault structure
echo ""
read -p "Initialize vault directory structure? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Creating vault structure...${NC}"

    mkdir -p "$VAULT_PATH/00-inbox"
    mkdir -p "$VAULT_PATH/10-daily/$(date +%Y)/$(date +%m)"
    mkdir -p "$VAULT_PATH/20-projects"
    mkdir -p "$VAULT_PATH/30-areas"
    mkdir -p "$VAULT_PATH/40-resources/concepts"
    mkdir -p "$VAULT_PATH/40-resources/snippets"
    mkdir -p "$VAULT_PATH/40-resources/references"
    mkdir -p "$VAULT_PATH/90-meta/templates"

    # Copy schema and templates if they don't exist
    if [ -d "$SCRIPT_DIR/examples/obsidian-vault/90-meta" ]; then
        if [ ! -f "$VAULT_PATH/90-meta/schema.md" ]; then
            cp "$SCRIPT_DIR/examples/obsidian-vault/90-meta/schema.md" "$VAULT_PATH/90-meta/"
            echo "  Copied schema.md"
        fi
        if [ ! -f "$VAULT_PATH/90-meta/tag-taxonomy.md" ]; then
            cp "$SCRIPT_DIR/examples/obsidian-vault/90-meta/tag-taxonomy.md" "$VAULT_PATH/90-meta/"
            echo "  Copied tag-taxonomy.md"
        fi
        if [ -d "$SCRIPT_DIR/examples/obsidian-vault/90-meta/templates" ]; then
            cp -n "$SCRIPT_DIR/examples/obsidian-vault/90-meta/templates/"* "$VAULT_PATH/90-meta/templates/" 2>/dev/null || true
            echo "  Copied templates"
        fi
    fi

    echo -e "${GREEN}Vault structure initialized.${NC}"
fi

# Optionally symlink to OpenCode config
echo ""
read -p "Symlink agents to ~/.config/opencode/agents/? (y/N): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    OPENCODE_AGENTS="$HOME/.config/opencode/agents"
    mkdir -p "$OPENCODE_AGENTS"

    for agent in "$SCRIPT_DIR/.opencode/agents/"*.md; do
        if [ -f "$agent" ]; then
            name=$(basename "$agent")
            if [ ! -e "$OPENCODE_AGENTS/$name" ]; then
                ln -s "$agent" "$OPENCODE_AGENTS/$name"
                echo "  Linked $name"
            else
                echo "  Skipped $name (already exists)"
            fi
        fi
    done

    echo -e "${GREEN}Agents symlinked.${NC}"
fi

echo ""
echo -e "${GREEN}=== Installation Complete ===${NC}"
echo ""
echo "Next steps:"
echo "  1. Review local/obsidian.yaml"
echo "  2. Open your vault in Obsidian"
echo "  3. Install Dataview plugin for queries"
echo "  4. Install Templater plugin for templates"
echo ""
